{{- if .Values.fullService.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "chart.fullname" . }}-full-service
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app: full-service
spec:
  replicas: {{ .Values.fullService.replicaCount }}
  selector:
    matchLabels:
      app: full-service
      {{- include "chart.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "chart.fullname" . }}-full-service
  template:
    metadata:
      annotations:
        {{- toYaml .Values.fullService.podAnnotations | nindent 8 }}
      labels:
        app: full-service
        {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      terminationGracePeriodSeconds: 30
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 2000
        fsGroupChangePolicy: "OnRootMismatch"
      containers:
      - name: full-service
        securityContext:
          capabilities:
            drop:
            - all
          readOnlyRootFilesystem: true
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.fullService.imagePullPolicy }}
        args:
          {{- toYaml .Values.fullService.args | nindent 10 }}
          - --listen-host=0.0.0.0
          - --fog-ingest-enclave-css=/usr/local/bin/ingest-enclave.css
          {{- if eq .Values.ledgerValidator.enabled true }}
            {{- if eq .Values.mirrorServiceTLS true }}
          - --validator=validator://{{ include "chart.fullname" . }}-ledger-validator:{{ .Values.ledgerValidator.listenPort }}/?ca-bundle=/certs/ca.crt
            {{- else }}
          - --validator=insecure-validator://{{ include "chart.fullname" . }}-ledger-validator:{{ .Values.ledgerValidator.listenPort }}/  
            {{- end }}
          {{- end }}
        ports:
        - name: full-service
          containerPort: {{ .Values.fullService.listenPort }}
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /data
        {{- if eq .Values.mirrorServiceTLS true }}
        - name: tls-cert
          mountPath: /certs
          readOnly: true
        {{- end }}
        resources:
          {{- toYaml .Values.fullService.resources | nindent 12 }}
      nodeSelector:
        {{- toYaml .Values.fullService.nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .Values.fullService.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.fullService.tolerations | nindent 8 }}
      volumes:
      {{- if eq .Values.fullService.persistence.enabled false }}
      - name: data
        emptyDir: {}
      {{- end }}
      {{- if eq .Values.mirrorServiceTLS true }}
        - name: tls-cert
          secret:
            secretName: {{ include "chart.fullname" .}}-lvn-cert-tls
      {{- end }}
  {{- if .Values.fullService.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      {{- toYaml .Values.fullService.persistence.spec | nindent 6 }}
  {{- end }}
{{- end }}