{{- if eq .Values.mirrorServiceTLS true }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "chart.fullname" . }}-public-cert
spec:
  dnsNames:
    - full-service-mirror-public.{{ .Release.Namespace }}.svc.cluster.local
  secretName: {{ include "chart.fullname" . }}-public-cert-tls
  issuerRef:
    name: internal-ca-issuer
    kind: ClusterIssuer
{{- end }}
