apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}-public
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app: mirror-service-public
spec:
  replicas: {{ $.Values.mirrorPublic.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
      app: mirror-service-public
  template:
    metadata:
      annotations:
        {{- toYaml .Values.mirrorPublic.podAnnotations | nindent 8 }}
      labels:
        {{- include "chart.selectorLabels" . | nindent 8 }}
        app: mirror-service-public
    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      containers:
      - name: mirror-service-public
        image: "{{ .Values.mirrorPublic.image.repository }}:{{ .Values.mirrorPublic.image.tag }}"
        imagePullPolicy: {{ .Values.mirrorPublic.imagePullPolicy }}
        args:
          - /usr/local/bin/wallet-service-mirror-public
          - --client-listen-uri=http://0.0.0.0:9091/
          {{- if eq .Values.mirrorServiceTLS true }}
          - --mirror-listen-uri=wallet-service-mirror://0.0.0.0/?tls-chain=/certs/tls.crt&tls-key=/certs/tls.key
          - --allow-self-signed-tls
          {{- else }}
          - --mirror-listen-uri=insecure-wallet-service-mirror://0.0.0.0/
          {{- end }}
        securityContext:
          capabilities:
            drop:
            - all
          readOnlyRootFilesystem: true
        ports:
          - name: http
            containerPort: 9091
            protocol: TCP
          - name: grpc
            containerPort: 10080
            protocol: TCP
          - name: grpc-tls
            containerPort: 10443
            protocol: TCP
        {{- if eq .Values.mirrorServiceTLS true }}
        volumeMounts:
          - mountPath: /certs
            name: tls-cert
            readOnly: true
        {{- end }}
        resources:
          {{- toYaml .Values.mirrorPublic.resources | nindent 10 }}
      {{- if eq .Values.mirrorServiceTLS true }}
      volumes:
        - name: tls-cert
          secret: 
            secretName: {{ include "chart.fullname" . }}-public-cert-tls
      {{- end }}
      nodeSelector:
        {{- toYaml .Values.mirrorPublic.nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .Values.mirrorPublic.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.mirrorPublic.tolerations | nindent 8 }}
