name: fsm-tag

on:
  push:
    branches:
      - 'main'
      - 'release/*'

jobs:
  # Only create a new tag if push to develop(prerelease) or main(release)
  # Will automatically bump "#patch" by default
  # Use "#major", "#minor", "#patch". "#none" in commit message to adjust bump.
  #
  # Requires mobilecoin-ci user R/W access and ACTIONS_TOKEN
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Github Tag Bump
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
          RELEASE_BRANCHES: main
          PRERELEASE_SUFFIX: pre
          WITH_V: 'true'
          DEFAULT_BUMP: patch
